name: Build Executable

on:
  push:
    branches: 
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  PROJECT_NAME: lss_fms5_alert_homeassistant

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: pip install -r requirements.txt -r requirements-build.txt

      - name: Define Build Name
        shell: bash
        run: |
          sha_suffix=""
          if [ "${{ github.ref_type }}" != "tag" ]; then
            sha_suffix="-${${{ github.sha }}:0:7}"
          fi

          BUILD_NAME="${{ env.PROJECT_NAME }}-${{ github.ref_name }}$sha_suffix_${{ runner.os }}_${{ runner.arch }}"
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV

      - name: Build Executable
        run: pyinstaller -F --hidden-import inquirer --hidden-import readchar --copy-metadata readchar -n $BUILD_NAME ${{ env.PROJECT_NAME }}.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} ${{ runner.arch }} Build
          path: dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
          files: dist/*
